### PR TITLE
Add `ExtUtils::MakeMaker` 7.00 requirements

### PR DESCRIPTION
**Pull request by zmughal**
for configure and build.

### CODE REVIEW

**Comment by petdance** [comment]
Updated.  Thanks.

**Comment by zmughal** [comment]
Thanks, I see the EUMM [downgrade](https://github.com/libwww-perl/HTML-Tagset/compare/4cc441c955cd148adf2caffd1d0aef6f01871f32~1..93cbaf7fb569ef8bf29c2375b656478aac34c531). This was causing intermittent build failures for the <https://github.com/kasei/attean> CI on older `perl`s that hadn't upgraded EUMM.

**Comment by petdance** [comment]
Sorry about that. The module hadn't been updated in 16 years, so I just kinda picked a starting point for EUMM.

**Comment by zmughal** [comment]
Oh I saw that. Good to see it getting some upgrades! Also, I noticed that the repo just got moved to the `libwww-perl` org! :-) An update to the metadata in `Makefile.PL` might make sense before the next release.

**Comment by petdance** [comment]
Good idea. I created #7 so the new folks can do what they need to do.

**Pull request closed without merging**
